modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="bluemoon"
version="1.0.0"
displayName="bluemoon"
displayURL="https://lucariki.top"
logoFile="logo.png"
credits="Hey"
authors="David"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bluemoon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration