modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="bluemoon"
version="1.0.0"
displayName="Bluemoon"
displayURL="https://github.com/LucaBarbaLata/blue-moon.corp"
logoFile="logo.png"
credits="Made with love by David and Luca"
authors="David, Luca"
description="Mod is still in BETA. So expect low quality textures, animations and overall experience. We are trying to make improvments every day :)"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bluemoon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration