name: Release Bluemoon.corp Mod

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create tags/releases

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod using Gradle
        run: ./gradlew build

      # This step gets the latest tag, increments the patch version, or sets 1.0.0 if none exists
      - name: Get latest tag and increment version
        id: versioning
        run: |
          TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/tags | jq -r '.[0].name' | sed 's/v//')
          if [[ "$TAG" == "null" ]]; then
            NEW_TAG="v1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG"
            PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          fi
          echo "new_tag=$NEW_TAG" >> "$GITHUB_OUTPUT"

      # Rename your built jar to include the version and forge info
      - name: Rename output jar with version and forge info
        run: |
          VERSION=${{ steps.versioning.outputs.new_tag }}
          VERSION=${VERSION#v}  # Remove leading 'v' from tag (v1.0.0 → 1.0.0)
          FORGE_VERSION="forge-1.20.1"  # Change this if you update forge version
          NEW_NAME="bluemoon-${VERSION}-${FORGE_VERSION}.jar"
          mkdir -p packaged
          cp build/libs/*.jar "packaged/${NEW_NAME}"

      # Create GitHub release and upload the renamed jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioning.outputs.new_tag }}
          name: Bluemoon.corp ${{ steps.versioning.outputs.new_tag }}
          body: ${{ github.event.head_commit.message }}  # commit message as changelog
          files: packaged/bluemoon-${{ steps.versioning.outputs.new_tag#v }}-forge-1.20.1.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
